spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kdt_order_jpa
    username: root
    password: 0917
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update     #create-drop   <-alter 오류로 update로 대체
    show-sql: true
    properties:
      hibernate:
        #format_sql: true         #SQL 줄바꿈 포함하여 여러 줄로 Hibernate 나온다.
        query.in_clause_parameter_padding: true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true